###########################################################
# Makefile for ...
###########################################################
PROGRAMMING_LANGUAGE=c
SOURCES=src/*.c \
        src/test/*.c
TARGET=rune

OTHER_MAKEFILES=

###########################################################

include Makefile-option
include $(shell emake --home)/Makefile.inc

###########################################################
# Additional segment provided by user
#
