###########################################################
# Makefile for ...
###########################################################
#! PROGRAMMING_LANGUAGE=|lang|

SOURCES=
TARGET=

OTHER_MAKEFILES=

###########################################################

#! include |fileopt|

include $(shell emake --home)/Makefile.inc

###########################################################
# Additional segment provided by user
#
